import pytest
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager

@pytest.fixture
def driver():
    service = FirefoxService(GeckoDriverManager().install())
    driver.add_argument("--window-size=1600,900")
    driver = webdriver.Firefox(service=service)
    yield driver
    driver.quit()